done Hw 2
AirstaNs/java-course-2023-backend-scrapper pull request #2
Opened 2024-02-25 20:44 UTC by AirstaNs

2024-02-29 14:38 UTC, nexen505 requested changes

2024-02-29 14:38 UTC, nexen505 commented on scrapper/src/main/resources/application.yml
> +  github: https://api.github.com
Проблема: не выполнено требование задания про использование значения по умолчанию, если он не указан.

Предложение: привести реализацию в соответствие с требованием.

2024-02-29 14:38 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scheduled/LinkUpdaterScheduler.java
> +    @Scheduled(fixedDelayString = "#{scheduler.interval()}")
Мысль: можно значительно упростить выражение и избавиться от лишнего бина, если воспользоваться знаком $ для получения конфигурационного свойства приложения по ключу.

2024-03-03 09:25 UTC, AirstaNs commented on scrapper/src/main/java/edu/java/scheduled/LinkUpdaterScheduler.java
> +    @Scheduled(fixedDelayString = "#{scheduler.interval()}")
Спасибо за рекомендацию, но тогда придется в конфигурации вместо секунд писать миллисекунды - иначе возникает ошибка парсинга

2024-03-05 13:42 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scheduled/LinkUpdaterScheduler.java
> +    @Scheduled(fixedDelayString = "#{scheduler.interval()}")
Это можно исправить, воспользовавшись другим форматом для `Duration`: https://www.mscharhag.com/java/iso8601-durations

2024-03-10 08:02 UTC, nexen505 approved these changes

2024-03-10 10:14 UTC, merged